msrv = "1.88"
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 6
too-many-lines-threshold = 80
type-complexity-threshold = 200
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
