#!/usr/bin/env bash
# マウントパス変換と docker-compose.override.yml 生成
#
# このファイルは source 専用 (直接実行しない)。
# start.sh / manage_mounts.sh から source して sync_compose 関数を利用する。
#
# 使い方:
#   source "${SCRIPT_DIR}/scripts/convert-mount-path.sh"
#   sync_compose <mounts_json> <override_file> <mount_base_dir> <caller_name>

# mounts.json から docker-compose.override.yml を生成する
#
# 引数:
#   $1 mounts_json     - mounts.json の絶対パス
#   $2 override_file   - 書き出す docker-compose.override.yml の絶対パス
#   $3 mount_base_dir  - コンテナ内のマウント親ディレクトリ (例: /mnt-host)
#   $4 caller_name     - ヘッダーコメントに記載する呼び出し元スクリプト名
sync_compose() {
    local mounts_json="$1"
    local override_file="$2"
    local mount_base_dir="$3"
    local caller_name="$4"

    local mount_lines
    mount_lines=$(jq -r --arg base "\${MOUNT_BASE_DIR:-${mount_base_dir}}" \
        '.mounts[] | "      - \(.host_path):\($base)/\(.slug):ro"' "$mounts_json" 2>/dev/null || true)

    # マウントが空なら override ファイルを削除
    if [[ -z "$mount_lines" ]]; then
        rm -f "$override_file"
        return
    fi

    # アトミック書き込み (tmp → mv)
    local tmp_file
    tmp_file=$(mktemp "${override_file}.XXXXXX")
    cat > "$tmp_file" <<EOF
# Auto-generated by ${caller_name} -- do not edit manually
services:
  viewer:
    volumes:
${mount_lines}
EOF
    mv "$tmp_file" "$override_file"
}
